# =========================
# ????? ? ????????????
# =========================
# ???? ???????? ??? ??????? .jar, ??????? ????? Ant ??? ?????????? ? ??????.
lib.dir=lib

# =========================
# ???? ? ?????????? ???????
# =========================
# ???????? ????? main-????? ???????
src.dir=src/main

# Java-???
main.dir=${src.dir}/java

# ??????? (????????, persistence.xml)
resources.dir=${src.dir}/resources

# Web-????? ???????: xhtml, css, js, WEB-INF/web.xml
web.dir=${src.dir}/webapp

# ?????
test.dir=src/test/java

# =========================
# ????????? ????? ??? ANT-??????
# =========================
# ??? ????????????? ?????????? Ant ????? ?????????? ????
ant.dir=ant
build.dir=${ant.dir}/build

# ???????????????? .class ??? web-??????????
classes.dir=${build.dir}/WEB-INF/classes

# ???? ????? ???????????? jar-?????????? ??? WAR
build.dir.lib=${build.dir}/WEB-INF/lib

# ????????? web.xml ??? ?????? WAR
build.web.xml=${build.dir}/WEB-INF/web.xml

# ???????????????? ?????
test.classes.dir=${build.dir}/test/classes

# =========================
# ???????? ?????????
# =========================
# ????????? ????? ? ???????????? ??????
dist.dir=dist

# ??? WAR-?????
war.name=WEB_LAB3_OPI.war

# ??? JAR-?????
jar.name=WEB_LAB3_OPI.jar

# MANIFEST.MF ??? JAR
manifest.file=${dist.dir}/MANIFEST.MF

# ????? ??? javadoc
javadoc.dir=${dist.dir}/javadoc

# ????? ??? junit-???????
junit.report.dir=reports

# ????? ??? ?????? ??????
report.dir=report

# =========================
# JAVA
# =========================
# ?????? Java ??? ??????????
compile.version=17

# ?????????????? ????????? JVM ??? ???????, ???? ???????????
vm.args=

# =========================
# NATIVE2ASCII
# =========================
# ????????? ????? ? ??????????????? ??????????? ??? ???? ????
alt.src.dir=alt-src

# ?????, ???? native2ascii ????? ?????????? ?????????
alt.build.dir=alt-build

# =========================
# DIFF / ?????????
# =========================
# ???? ? diff ??? ?????????? ???????
diff.file=failed_revision_diff.patch

# ???? ?? ??????? ignore
ignore.file=git-ignore.properties

# =========================
# HELIOS / DEPLOY
# =========================
# ???? ????? ?? helios
scp.user=s465439

# ????? ?????
scp.host=helios.se.ifmo.ru

# ???? SSH
scp.port=2222

# ???? ?????????? ????? ?? helios
scp.helios.dir=/home/studs/${scp.user}/WEB_LAB3_OPI

# ?????? ????? ?? ??????? ???.
# ??????? ??????, ????? ?? ??????? ???????.
scp.password=Crri@2274

# =========================
# ????????? WILDFLY
# =========================
# ????? deployments ?????? ?????????? WildFly
wildfly.deploy.dir=${user.home}/Downloads/wildfly-39.0.0.Final/standalone/deployments

# ?????? ??????? WildFly
wildfly.script=${user.home}/Downloads/wildfly-39.0.0.Final/bin/standalone.sh