lib.dir=lib

src.dir=src/main
main.dir=${src.dir}/java
resources.dir=${src.dir}/resources
web.dir=${src.dir}/webapp

test.dir=src/test/java

ant.dir=ant
build.dir=${ant.dir}/build
classes.dir=${build.dir}/WEB-INF/classes
build.dir.lib=${build.dir}/WEB-INF/lib
build.web.xml=${build.dir}/WEB-INF/web.xml
test.classes.dir=${build.dir}/test/classes

dist.dir=dist
war.name=WEB_LAB3_OPI.war
jar.name=WEB_LAB3_OPI.jar

manifest.file=${dist.dir}/MANIFEST.MF
doc.manifest.file=${dist.dir}/DOC-MANIFEST.MF
javadoc.dir=${dist.dir}/javadoc

junit.report.dir=reports
report.dir=report

compile.version=17
vm.args=

alt.src.dir=alt-src
alt.build.dir=alt-build

diff.file=failed_revision_diff.patch
ignore.file=git-ignore.properties

checksums.dir=${build.dir}/checksums

scp.user=s465439
scp.host=helios.se.ifmo.ru
scp.port=2222
scp.helios.dir=/home/studs/${scp.user}/WEB_LAB3_OPI

wildfly.deploy.dir=${user.home}/Downloads/wildfly-39.0.0.Final/standalone/deployments
wildfly.script=${user.home}/Downloads/wildfly-39.0.0.Final/bin/standalone.sh